apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend_deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend_deployment_label
  template:
    metadata:
      labels:
        app: backend_deployment_label
    spec:
      containers:
        - image: suryasuraj/backend_image:latest
          name: backend_container
          resources:
            requests:
              cpu: "100m"
              memory: "150Mi"
            limits:
              cpu: "200m"
              memory: "300Mi"