apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend_hpa
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend_deployment
  metrics:
    - type: Resource
      resources:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50