apiVersion: v1
kind: Service
metadata:
  name: backend_service
spec:
  selector:
    matchLabels:
      app: backend_deployment_label
  type: NodePort
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
