apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend_deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend_deployment_label
  template:
    metadata:
      labels:
        app: frontend_deployment_label
    spec:
      containers:
        - image: suryasuraj/frontend_image:latest
          name: frontend_container
          resources:
            requests:
              cpu: "100m"
              memory: "150Mi"
            limits:
              cpu: "200m"
              memory: "300Mi"

              
