apiVersion: v1
kind: Service
metadata:
  name: frontend_service
spec:
  selector:
    matchLabels:
      app: frontend_deployment_label
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP